// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqxjspdkhoogdewuvrcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeGpzcGRraG9vZ2Rld3V2cmN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDAxOTksImV4cCI6MjA3MDA3NjE5OX0.EzJ66GOEYJq7aoAu2zcpeoB5pFBY1hSUBHt6PBP9-wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});